Controllers/CoursesController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StARKS.Data;
using StARKS.Models;

namespace StARKS.Controllers
{
    public class CoursesController : Controller
    {
        private readonly WebAppContext _context;

        public CoursesController(WebAppContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .FirstOrDefaultAsync(m => m.Code == id.ToString());
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Code,Name,Description")] Course course)
        {
            if (IsCourseCodeExist(course) == true)
            {
                ModelState.AddModelError("Code", "CourseCode already exists");
            }

            if (ModelState.IsValid)
            {
                _context.Add(course);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }
            return View(course);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Code,Name,Description")] Course course)
        {
            if (id != course.Id)
            {
                return NotFound();
            }

            if (IsCourseCodeExist(course) == true)
            {
                ModelState.AddModelError("Code", "CourseCode already exists");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Home");
            }
            return View(course);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _context.Course.FindAsync(id);
            _context.Course.Remove(course);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        private bool CourseExists(int id)
        {
            return _context.Course.Any(e => e.Id == id);
        }

        private bool IsCourseCodeExist(Course course)
        {
            return _context.Course.Any(x => x.Code == course.Code && x.Id != course.Id);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using StARKS.Data;
using StARKS.Factores;
using StARKS.Models;
using System.Diagnostics;
using System.Linq;

namespace StARKS.Controllers
{
    public class HomeController : Controller
    {
        private readonly WebAppContext _context;
        private readonly ViewModelFactory _viewModelFacotory;

        public HomeController(WebAppContext context, ViewModelFactory factory)
        {
            _context = context;
            _viewModelFacotory = factory;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View
                ( 
                    _viewModelFacotory.CreateMainTableView() 
                );
        }

        // Create mark if don't exist, or edit if exist, of delete mark if the user submit empty MarkValue
        [HttpPost]
        public JsonResult MarkProcessing([Bind("CourseCode,StudentId,MarkValue")] Mark mark)
        {
            if (ModelState.IsValid)
            {
                if (!IsMarkExists(mark))
                {
                     CreateMark(mark);
                }
                else
                {
                    EditMark(mark);
                }

                //  Send "Success"
                return Json(new { success = true, responseText = "Your message successfuly sent!" });
            }
            //  Send "false"
            return Json(new { success = false, responseText = "The attached file is not supported." });
        }


        public void CreateMark(Mark mark)
        {
           _context.Add(mark);
           _context.SaveChanges();
        }

        //Edit or delete
        public void EditMark(Mark mark)
        {
            var markDb =  _context.Mark.FirstOrDefault(e => e.CourseCode == mark.CourseCode && e.StudentId == mark.StudentId);

            if(mark.MarkValue != null)
            {
                 markDb.MarkValue = mark.MarkValue;
                _context.Update(markDb);
            }
            else
            {
                _context.Mark.Remove(markDb);
            }
            _context.SaveChanges();

        }

        public void DeleteMark(int id)
        {
            var mark = _context.Mark.Find(id);
            _context.Mark.Remove(mark);
            _context.SaveChanges();
        }

        private bool IsMarkExists(Mark mark)
        {
            return _context.Mark.Any(e => e.CourseCode == mark.CourseCode && e.StudentId == mark.StudentId);
        }

        [HttpGet]
        public IActionResult FilterStudents(string searchTerm)
        {
           var students = _context.Student
                .Where(s =>
                s.FirstName.Contains(searchTerm) ||
                s.LastName.Contains(searchTerm));

            return Json(new
            {
                results = students.Select(s => new
                {
                    id = s.Id,
                    text = s.FirstName + " " + s.LastName,
                })
            });
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/StudentsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StARKS.Data;
using StARKS.Models;

namespace StARKS.Controllers
{
    public class StudentsController : Controller
    {
        private readonly WebAppContext _context;

        public StudentsController(WebAppContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Student
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,Address,City,State,DateOfBirth,Gender")] Student student)
        {
            if (ModelState.IsValid)
            {
                _context.Add(student);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }
            return View(student);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Student.FindAsync(id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,Address,City,State,DateOfBirth,Gender")] Student student)
        {
            if (id != student.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(student);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentExists(student.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Home");
            }
            return View(student);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Student
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var student = await _context.Student.FindAsync(id);
            _context.Student.Remove(student);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        private bool StudentExists(int id)
        {
            return _context.Student.Any(e => e.Id == id);
        }
    }
}

Views/Home/Index.cshtml
@model StARKS.Models.MainTableViewModel

@{
    ViewData["Title"] = "Home Page";
}

<label class="row">
    <div class="col-6">
        <select class="col-5" id="filterStudents"></select>
        <select class="col-5" id="filterCourses">
            <option></option>
            @{
                foreach (var course in Model.Courses)
                {
                    <option value="@course.Code">
                        @course.Name
                    </option>
                }
            }
        </select>
    </div>
    <div class="col-6 float-right">
        <div class="float-right">
            <b/>
            <a asp-controller="Courses" asp-action="Create"> Add Course </a> |
            <a asp-controller="Students" asp-action="Create"> Add Student </a>
        </div>
    </div>
</label>
<table id="mainTable" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">
    <thead>
        <tr>
            <th>
            </th>
            @foreach (var course in Model.Courses)
            {
                <th id="@course.Code">
                    <a class="align-middle" asp-controller="Courses" asp-action="Details" asp-route-id="@course.Code">
                        <b>@course.Name</b>
                    </a>
                </th>
            }

        </tr>
    </thead>
    <tbody>
        @foreach (var student in Model.Students)
        {
            <tr id="@student.StudentId">
                <td>
                    <a asp-controller="Students" asp-action="Details" asp-route-id="@student.StudentId">
                        @student.StudentFullName
                    </a>
                </td>

                @foreach (var mark in student.Marks)
                {
            <td>
                <div id="student" hidden value="@mark.StudentId"></div>
                <div id="course" hidden value="@mark.CourseCode"></div>
                <input id="mark" type="number" value="@mark.MarkValue" min="6" max="10" pattern="^[6,7,8,9,10]+$|^$">
            </td>
                }
            </tr>
        }
    </tbody>
</table>

@section scripts {

    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script type="text/javascript">

    $(document).ready(function () {

        // Validate and trigger submit on Focus Out
        $("input#mark").focusout(function () {

            if ($(this)[0].checkValidity()) {

                $(this).submit();
            } else {
                alert('Out of range');
            }
        });

        // Mark Processing
        $("input#mark").submit(function () {
           
            var studentId = $(this).siblings('#student').attr("value");
            var courseId = $(this).siblings('#course').attr("value");
            var mark = $(this).val();

            $.ajax({
                type: "POST",
                url: '@Url.Action("MarkProcessing", "Home")',
                data: {
                    "courseCode": courseId,
                    "studentId": studentId,
                    "markValue": mark
                },
                success: function (recData) { alert('Successfully updated'); },
                error: function() { alert('A error'); }
            });
        });

        // Remote filltering, search students in the database
        $('#filterStudents').select2({
                ajax: {
                    url: '@Url.Action("FilterStudents")',
                data: {
                    "searchTerm": function () {
                        return $('.select2-search__field')[0].value
                    }},
                },
                placeholder: "Filter students...",
                allowClear: true,
            minimumInputLength: 1
        });

        // Hide or show rows for student filltering
        $('#filterStudents').on('change', function (e) {
            var id = $(e.currentTarget).val();
            if (id != null) {
                $('tbody tr[id]').hide(); // hide all rows
                $('tbody tr[id=' + id + ']').show(); // show selected row
            } else {
                $('tbody tr[id]').show();
            }
        });

        // Selecting students from Model
        $('#filterCourses').select2({
                placeholder: "Filter courses...",
                allowClear: true,
        });

        // Hide or show columns for filltering
        $('#filterCourses').on('change', function (e) {

            var id = $(this).children("option:selected").val();

            if (id != null && id != "") {
                $('thead th[id]').hide(); // hide all headers
                $('td:has(#course)').hide(); // hide all row
                $('thead th[id=' + id + ']').show(); // show only selected header
                $('td:has(#course[value=' + id + '])').show(); //show column
            } else {
                $('thead th[id]').show();
                $('td:has(#course)').show();
            }
        });

    });
    </script>
}